* 计算机启动过程
** 电源自检
   - 电压和电流稳定后, 供电系统会发送一个 "Power Good" 信号给主板
   - 微处理器定时芯片接收 "Power Good" 信号. 从电源键按下到 "Power Good" 信号
	 发生大约在 0.1 到 0.5 秒之间.
   - "Power Good" 信号没有到达之前, 为了防止系统在不稳定的电源下运行,
	 定时芯片不断地向 CPU 发送重置信号(效果就和手动按重置键一段时间一样).

** 微处理器定时芯片接收 "Power Good" 信号
   正如上面所说, 微处理器定时芯片接收 "Power Good" 信号以后, 重置信号被关闭.
   CPU 开始执行. 但是这个时候内存中是空的, 里面的代码不能被执行, CPU 产商做了
   一些处理, 使得 CPU 执行 ROM "FFFF:0000" 处的代码.

** CPU 执行 ROM BIOS 的代码
   上面的条件满足以后, CPU 就会载入和执行 ROM BIOS "FFFF:0000"处的代码,
   基本上只是一条跳转到系统 BIOS 真正的启动代码处的指令.

** BIOS 执行 POST (Power-On Self-Test):
   BIOS 的启动代码做的第一件事是 POST, POST 通常做一些硬件的检查,
   确保计算机的硬件都能正常工作, 比如内存, CPU 等. 在此过程中发生的错误
   分为致命和非致命的, 非致命的错误一般只是在屏幕上显示错误的信息, 致命的
   错误会发出很多 beep 声, 自检成功后, 也会发出一声简单的 beep 声.

** 初始化显卡设备
   这一步, BIOS 初始化显卡设备. 它会查找显卡的 BIOS 代码, 一般在内存的
   C0000 到 C7800 处. 系统 BIOS 执行找到的显卡 BIOS 代码来初始化显卡,
   大部分显卡会在屏幕上显示一些显卡的信息, 比如 介绍生产厂商, 图形芯片类型
   等内容. 如果发生了错误, 会在屏幕上显示一些 "XXXX ROM Error" 的错误.

   这就是为什么在看到其他系统信息之前, 总是先看到显卡的信息的原因.

   一个问题: 如果计算机没有显卡, 那么能不能正常启动系统?

   答案应该是取决于 BIOS 的设置, 可能有的 BIOS 在这一步就报错退出了,
   有的 BIOS 会允许系统在没有显卡的环境下正常运行. 不过似乎现在大部分的 BIOS
   都支持没有显卡的启动. 另外在 QEMU 上模拟的 BIOS 也支持在没有显卡的情况下
   启动.

** 初始化其它设备
   查找是否有其它设备的 BIOS 代码, 如果有, 就执行这些代码初始化它们. 一般会在
   C8000 处找到 IDE/ATA 的 BIOS 代码.

** 显示 BIOS 的启动画面
   这步 BIOS 会在屏幕上显示一些产商, BIOS 版本等的信息.

** 测试设备
   初始化完设备以后, BIOS 会执行一些系统的测试, 包括检测和显示 CPU 的类型和
   工作频率, 测试所有的 RAM, 之后 系统 BIOS 将开始检测系统中安装的一些标准
   硬件设备, 包括硬盘, 光驱, 串口, 软驱等, 绝大多数 BIOS 还会自动检测和设置
   内存的定时参数, 硬盘参数和访问模式等. 标准设备检测完毕后, 如果 BIOS 支持
   即插即用设备, BIOS 还会检测和配置系统中安装的即插即用设备, 每找到一
   个设备, BIOS 会为该设备分配中断 INT, DMA 通道和 I/O 地址等资源.

   然后, BIOS 会在屏幕上显示整体的系统信息.

** 更新 CMOS 中的数据
   接下来, BIOS 会从 CMOS 中读取配置信息, 这些信息包括启动顺序, 硬盘大小,
   日期时间等信息.

** 加载操作系统
   BIOS 从上一步得到启动的顺序后, 会去读启动设备的第0面, 第0柱面, 第0扇区, 也就是
   MBR(Master Boot Record), 如果最后两个字节是 0xAA55, 那么这个扇区就是有效的
   启动扇区. 把这个扇区加载到 0x7C00 出开始执行, 以后的执行就交给了 OS.

** Refer:
   - [[http://www.comptechdoc.org/hardware/pc/pcboot.html][The Booting Process of the PC]]

   - [[http://www.pcguide.com/ref/mbsys/bios/bootSequence-c.html][System Boot Sequence]]

* 实模式
* Hello World
